### ISSUE TITLE
Script is bugs 

### ISSUE THREAD

**Issue by asifagaria** [QuickBox/QB#113]
i'm install
ubuntu 16.04
ubuntu 16.04.1
ubuntu 16.04.2
ubuntu 16.04.3

and all time this script delete dhcp on ubuntu os and error showing fail to send 300 byte long packet error
enp4s0f0
solve it

**Comment by JMSDOnline** [comment]
Ok.

> and all time this script delete dhcp on ubuntu os

No, the script doesn't have anything to do with your servers DHCP. Nowhere does it modify this. It does have an option to set an FQDN. If you're using Online.net (as I assume due to the interface you mentioned), it's probably good to do that. This is an issue with Online.net. See [here](https://plaza.quickbox.io/t/server-unreachable-upon-rebooting-after-quickbox-installation/4085).

> solve it

Well, there are certainly nicer ways to make a request, or issue a report for that matter. 😉
