### ISSUE TITLE
rTorrent not installed couchpotato doesn't load 

### ISSUE THREAD

**Issue by upcboy** [QuickBox/QB#47]
I've done a clean install on 16.04

After install rTorrent is not installed was able to manually install it with apt install rTorrent

Tried installing couchpotato from packages. When clicking the link to open couchpotato it opens the the dashboard back up. 

I have reinstalled server 16.04 twice and ended with the same results.

**Comment by JMSDOnline** [comment]
1. I don't offer support (usually) through this, so please reach out to me at plaza.quickbox.io
2. Since this is an issue with the recent openssl update, do this to fix your rtorrent install. `apt -y install rtorrent`, then issue a restart, either from your dashboard or via the command `systemctl restart rtorrent@USERNAMEHERE`
3. For your couchpotato issue, there is a thread that answers this on the forums... [HERE --> couchpotato-redirect-to-dashboard](https://plaza.quickbox.io/t/couchpotato-redirect-to-dashboard/2052/19). This should be fixed, however, I will still take a look into this and possibly write out a default template like Ive done with Jackett, Sonarr, etc etc.

**Comment by upcboy** [comment]
I tried to PM you at plaza.quickbox.io but It said i wasn't allowed to for some reason.

Is this not the correct place to post bugs? rTorrent not starting from a clean install(I understand the openssl change isn't quickbox.io's issues ) and Couchpotato not loading on said clean install both seem to be bugs  If this isn't the best place to report things I'll make sure to post in the correct place in the future.

**Comment by JMSDOnline** [comment]
I updated your permissions. I will send you a PM as well. Let's continue the discussion there. The correct place for posting is technically (in the forum #Bugs category, here)[https://plaza.quickbox.io/c/bugs]. This is an issue understandably and I am sacrificing my night to get this resolved. 😉
