### ISSUE TITLE
Custom adds to menu disapear

### ISSUE THREAD

**Issue by JuezFenix** [QuickBox/QB#75]
After update, my custom menu entries, simply totally erased.

**Comment by dragon36** [comment]
I second that, same thing happened here.

**Comment by JMSDOnline** [comment]
I adjusted the updater and this is 100% my error.

Here's the commit fix on the updater, apologies once more for the issues this may had brought upon anyone. If anyone is stuck because they feel like their dashboards are borked (from the update), please do not hesitate to PM in the chat or on the Plaza.

https://github.com/QuickBox/QB/commit/d2ce0cd98cc946f84e06252a7aacaee532c8a003
