### ISSUE TITLE
Dashboard widgets borked after 0937a51

### ISSUE THREAD

**Issue by Asexual** [QuickBox/QB#80]
Just updated after about 4-5 days, via cli boxupgrade. I saw suggestions of updating once more but didn't really see the change that would fix the current issue for myself given it was the same commit as of today so just incase i did the upgrade once more but alas no luck. Curious if anyone has any ideas seeing as i am the only one running into the previous closed issue. Thx

**Comment by JMSDOnline** [comment]
I adjusted the updater and this is 100% my error.

Here's the commit fix on the updater, apologies once more for the issues this may had brought upon anyone. If anyone is stuck because they feel like their dashboards are borked (from the update), please do not hesitate to PM here in the chat or on the Plaza.

https://github.com/QuickBox/QB/commit/d2ce0cd98cc946f84e06252a7aacaee532c8a003
